kind: ConfigMap
apiVersion: v1
metadata:
  name: mq01ha-mqsc
  namespace: cp4i-mq
data:
  mq01ha-mqsc.mqsc: |-
    define ql(APPQ) DEFPSIST(YES)
    define ql(APPQ1) DEFPSIST(YES)
    DEFINE CHANNEL(MQ01HACHL) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER')
    set chlauth(MQ01HACHL) TYPE(BLOCKUSER) USERLIST(NOBODY)
    REFRESH SECURITY TYPE(CONNAUTH)
  mq01ha-nativeha-tls.ini: |
    Service:
        Name=AuthorizationService
        EntryPoints=14
        SecurityPolicy=UserExternal
---
kind: Secret
apiVersion: v1
metadata:
  name: mq01ha-qm-tls
  namespace: cp4i-mq
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUV0VENDQXAwQ0ZFamc5RzBVY2RpTjdoRlN1Rkp2cDNoVmJzMnNNQTBHQ1NxR1NJYjNEUUVCRFFVQU1CZ3gKRmpBVUJnTlZCQU1NRFhObGJHWnphV2R1WldRdFkyRXdIaGNOTWpVd016STBNREF6TURNMFdoY05Nall3TXpJMApNREF6TURNMFdqQVdNUlF3RWdZRFZRUUREQXR1WVhScGRtVm9ZUzF4YlRDQ0FpSXdEUVlKS29aSWh2Y05BUUVCCkJRQURnZ0lQQURDQ0Fnb0NnZ0lCQUpBajZLSWZ2QW5meVExTEZKWTVYczJTdnVYc1JnRU05QWhvRGpvNVVwbWwKc1MzY0hycGVhYVVPcDdiVzJmc1ptWUN6MnBjQ09YS2R4UlE5QzJNd3Q1amJiVFZBeHZ1VFpnYTlmNTdPYjducgpKa1hocWh2M1QraVB4OWJVWlowWTlmT1lsT2V4TWpBTDlXeHRmQTJUbm5JV0gvMGRJQXZ0TmNwdERhQzRSNjJGCmlLYjFkMFRrUndsSm9uQnQxaWRtSFNjZFJOcXhqNWhzMnNTWVUxMFNpZHpPc0c5UmxwZ2xaMFV6dkxJV1Q5RmIKYnZPQ01oSFIyeEUyRHI0T29qZXYxOThjd21VdklaTFFrUTdERmZ3elJLN0cxd2RWaGt5ZklnaExaSmlISEZXbgo1bDY0SzI1d3Rod1A0QWk4czFpakN2K3Ezb2RuczVjS1p4L09GSDArSVV6eUtiWFZXSVJCQ2FIR1d2ZkRlYTVBCjNBamF3TmZzMy9SODBNS1NqVjU3NjRWcFNmUjR1VENndW9QL1RIOE0wOHdqeCt0ZlJWYk5zTmlWTjNHdU5EYlkKMzN4dUpKeWc2bzVEY3FHYjlOUWorc3pWMzUxVU9HZ1FOZC95ZjhySHBkYVNpUmJqQU9CS2lQNUdIaFRlTmFkLwpKd2JWT2k3UkhPNEpWbmdLdWU4UmgycTdxSmZFVTVlMDlQcXNrTW53RTdOWm55dnYrNy85WjNseFF1dmV1ejdSCmZSM1pLUjhmbU1iUERyQ1RlKzJXaVhGVUVZbWQ4NlRtcG00b1o5bEFtQmY0NGpLTGhlT281VGIxbmNWenBWQTYKZW1TWXlucGV1MGx5K3FIKzVpajd1QmxhSWdtODlQMmt0RkRrMFZJVTJkaEhObmkwTEpxbHdHcGVNU09pOWw0WgpBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRU5CUUFEZ2dJQkFCakhwMjZSWmdKVStWSkpFbGtPSWQ3eHV2Sk9ZQnpDCnZRZUJFcWNGcmhCNnZOSlE2dlFYTlBUOVlpVGxNQUNZbjlqaTRyZVl5S3VUQ0hSeGtpUk5JRmdpZXQ0N2IrNjkKMkhWMmRjS05KNE5LNnpjVU5IbDNDcTF4MVVXM1FGaHljYnpGVURSbmdiQWhPMFNJQ2NQVGtzSFdRYjVidnkySwpyZzdvL0hxaHZEM3lPMUxrRktMaUtyK3Z1M3QvMWlTZGlaelFXbHUvdjR2ZGluTWtGK1M1NGdVOVNZZnFqSmlFCjFqd2tlTXVCaTNGZlF2RGExR05PUFdOYzNOZk9HZnhLYUU3OVdORU9PcTNDQ2VHS2x2TGRkbGg1eWovVDE4Y0cKR09aTHlQZ2dtWk05dnJ6SFRTeEJDN0lFa1FFRXlqR2ZBYUlDL0RWYTNYd05OQ01iMklXVFFWT05ZV0hzdGtmTAppZEdwR1JnR0w4VlJDMXJlQmlJNU96a0xyN1dXTEtUdDVTbWdXcVZaV3NMWlVQUGxnRFc2QXVJV3lvL3dTQ2tzCmFoaG53eFN0b09FelRmbFgwc0x4SzJ2OHIxTXd0UzFaZjl2Y0dNeHZ6K0tFOU1ZVkp0cTRIOHJaQjJnWTFpeEsKejhOZXFjcHF4Y0FEZmVOK1VtOVNzQmppa0RWQUlKNyt3OTZyTDlENiszUERkNmxNWENNQzcrR3VqWnNhNTNzeApmVGs1UjFZb1pSZ1FIVElkSUM2OWZEZzY3b3FTNENtUXVkeGpOdWprN1MxN1U0QmVqczRwVUNJaFptdEhSQnczCmw2RUk4RFlFT01MSjlWbG5pTzVHQXpGaUhlRXFKaWlpWXkzNlBjMUNEWElVZ1JDcHNNeU5uOW96bi9DUEJXT1EKSGw5ejk4TEJvMHZpCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQ1N3d2dna29BZ0VBQW9JQ0FRQ1FJK2lpSDd3SjM4a04KU3hTV09WN05rcjdsN0VZQkRQUUlhQTQ2T1ZLWnBiRXQzQjY2WG1tbERxZTIxdG43R1ptQXM5cVhBamx5bmNVVQpQUXRqTUxlWTIyMDFRTWI3azJZR3ZYK2V6bSs1NnlaRjRhb2I5MC9vajhmVzFHV2RHUFh6bUpUbnNUSXdDL1ZzCmJYd05rNTV5RmgvOUhTQUw3VFhLYlEyZ3VFZXRoWWltOVhkRTVFY0pTYUp3YmRZblpoMG5IVVRhc1krWWJOckUKbUZOZEVvbmN6ckJ2VVphWUpXZEZNN3l5RmsvUlcyN3pnaklSMGRzUk5nNitEcUkzcjlmZkhNSmxMeUdTMEpFTwp3eFg4TTBTdXh0Y0hWWVpNbnlJSVMyU1loeHhWcCtaZXVDdHVjTFljRCtBSXZMTllvd3IvcXQ2SFo3T1hDbWNmCnpoUjlQaUZNOGltMTFWaUVRUW1oeGxyM3czbXVRTndJMnNEWDdOLzBmTkRDa28xZWUrdUZhVW4wZUxrd29McUQKLzB4L0ROUE1JOGZyWDBWV3piRFlsVGR4cmpRMjJOOThiaVNjb09xT1EzS2htL1RVSS9yTTFkK2RWRGhvRURYZgo4bi9LeDZYV2tva1c0d0RnU29qK1JoNFUzalduZnljRzFUb3UwUnp1Q1ZaNENybnZFWWRxdTZpWHhGT1h0UFQ2CnJKREo4Qk96V1o4cjcvdS8vV2Q1Y1VMcjNycyswWDBkMlNrZkg1akd6dzZ3azN2dGxvbHhWQkdKbmZPazVxWnUKS0dmWlFKZ1grT0l5aTRYanFPVTI5WjNGYzZWUU9ucGttTXA2WHJ0SmN2cWgvdVlvKzdnWldpSUp2UFQ5cExSUQo1TkZTRk5uWVJ6WjR0Q3lhcGNCcVhqRWpvdlplR1FJREFRQUJBb0lDQUEyb3dYcGZuSCtwQzlIdExBSENaUWdCCklJTUVYV3ZyRU5NZEhVQUtQNWdjMmduNUFwWnhyUHc5dzhueFdVM1Ewcm1lRVpoZTF4ZlQrS0dlMlUzb2gzVisKVWI2S3FYQ2N1cjNueGtqRDBsV2hnWXA4eEpTSzNyRXdzdVRhVXRqTXpUM3MxeXVQb0t4cDdiTjlPcFRFeU82Ugp4eTFDemM4amh3WHNTSzdTMThRTFUvUlNiWitETEhJbVhyVGR5NzRIRUxzc3JHSTNFbDhFN2NSVWxRM01YSEVtCnl4UjVmRlpsc1FBZlU0SGkyR1NFRUNNV1V1MWFZREtrMTBmT2RqUGx2NFMrb25OWlFJcTdwZ3RxbEZKR2YzczYKajVUNzExSzZmOHllYkdXQjVENy92clo2S0c5NlVkK2Q1NEtjY3poeWx1Kzhmd01BNGtWdGNIRlVvNTlzdkZYOApaTFZiQkhvWUJOODlRdFZONm5Td2Y0R3BhaVFYeUFaUEgwWk5hS1RwQllmTDZDaUgxQjFPWmo4bHlsbEdMTnp5CldDdzlrbzhnSXJiaWd3bHJERWNLaU14dUlldUdleFlhZ0tZTzYvUk1yOUVGRW1zLzg5ZWVSQlRmdWtnN2xGNXQKckpVbU1oT3FjS2hIMXE4ak1mcTZEaEk0WlZlSW9DKzF6bm1MS3d5dXl2R2luaEFDMTZlNDZiQ0tmdkkxOEtOUgovUFN2cUJzTDFIYjVjTzVQb0xZVXVHUlBzZ0JMdW1ibE5lU0xFKzNhSkNHL1h1dW1GOUJFNWg0cUFJNFpZNnMwCjlzVytHR1ZrejNzWEt2MUlxcTlRZFBJa0VFSHYwRkpTZGJGQ1ZXb3JDNk9UOHZ0R29pRDBqY09lQTNZQmo5NUIKZk1YQ3BWazQ2cW1PbVdoNU9RSjdBb0lCQVFESzJXa2QvaXJCT0NoaEViQWN2ZHA0T2U2OXBsTWhPRGRUVkQ4YQo1U2dDWWJSRTMyL2k0b3BtTHlzY09sVDN2TlpnZldzSFhNRGlyd3poWFNEVzYyTzJDb1BVS0ttRWl1bFlqRWNLClFPbi9rMXZKcTFUUmRnZWtnVm16Tll3YkpVQTRZeUh0NlpVcE9UUzk2SnVVVE03WlYwa0lzck5nOXNwSXdxZlYKZm0vTUxnS04wR3pnTFlKcWZZRFZObkN4ZmxhSWtEMGhsYzFnQ3NZU2k0SjJqNWx2S1NKKy9jYW1LTzI0eUZyMQpHQzNHelY3VzF6aTQ5YldzdjQ3akxZU2FUMm9TT2t2dU56OUswTFRRbHZicmRndXZKN1ZmRG9hRmc5ZStjUE9CCmo5T1ZVMWljTGxvUmU5TDhONzJoWHVBaExTUW5yam5hUkNibFd6N3RJRzRpb1BoekFvSUJBUUMxNkhSMnp2cDgKZGM5TE1OQVV1RXh3SlRKL3RoQmtXZzRjODY5bW9wMUFVNlBkTmFKek9sWG84allJbE84TnVlWlJOVlREWVBEOAptQnNBWWNUdlhxcit1cmNRVUZlWEJVa04wdVVybEJWUW03aW0vV0tHdG5DOVZZdnNRL1hYeDViZG1adTVYNjZ5CmxINGowVm1pNWxzTUlRN2hqSk5vdmFjRTd4b3hYOXdiSWx3ajRhbmYrb2Z4Wkk3QXc3MnUxVWpzSzRoZVhwVGMKZmFvZXJ5MklIWStFK1pyRTJ4R3JMcEg2Ry9oTDh5TkF5RmNFcHA5QkR6dHZKSTVaZjlNRGFSMnFPam1qVngwQwo3UlhGRDl0TnpBeitabUpFTlZqUXNhTURrOXFpdk5sVDcwbzZ1VlJNd0tPc2p2UGFMKzlkUkNKNStBWjhTcStpClR4amhzNmFTOTBoREFvSUJBRXJiYW9CSUFJMG5aVGRWS0xHaW1sSE54ejJ6ZUhBRTU5M1hkQ1kvdE1FVVAwcy8KVFhIaitnRDFuU29nbUtTSHluRDNONTBTN0pkNjAvMEN1aEMxOHlrRnZscDMydjd2cUdjbDlUMWljVGdBc0ZtKwo0V0VlOW5rTnh3VnNXRlRZTFZmaHRXNnZ5WHphQUkyb25tbGU0dUt2NUdMU1Y0SUw4T0JpL1Q2N0Z4UzVVZlgxCm1ZZ3RJemliTWdUOHZ4K3hLTXZpdHJ5REpMUXhwYURJWFEvVnRHQ2lSSG1xdXprc1YzWGVjanFLZnJJanJjRUkKMFlUb0gvQXRETlRuUWswVHkyZ0luV2ErZXB2b1l5R3E1RnBHU00rTmp0QVNjekFvVkdDU0hEcU8waDBFRWVvbwo3TklRNk81c3Y0MGlqd0dQUUExb3JTN1FBYTZZT3FPVldTOXNTZU1DZ2dFQUdXN3QwYXF3dFBRWHpwQjlsMWdKClArakRmYjJyM3d3RVN5SDdGU09KVHZRaXhndjRzWm1uWjFGdUlwY0lNV2diZnFFeFA3dnZGYklDbkhRTy85VEIKbmFubmJIMS9NWnRJa29rNUIzWEY0U1pVayt4N2VSQkxCUDNQK1hHckRzZFdIWmViZ1RpU2lWOWZuNHhtdHZMMApLZWI1V0ttNTlud0Z2UmZkRnFncmN4UER4RFNKOXNubGRlZTBXZGxFVFF4L0RKNHRpOXczZmZpSDc1QllrbDVuCnNaVGdnY09MWGQ2K0JEVWk2eU9NZTBOSGYxdjRpalVoL3pFaVFmc3dPcHJZemZNa0dlVlZKaEtWNTU2RzhBS20Ka204b01CY3hXc1JyWVZXcnpQTVFnNzdDSnlIQVdwYllpNGpWS1Yxb1h5Ym1seDBKY3hsU0l5UmgrelNPQnFCUwpWd0tDQVFFQXNGbHpXa3MvRnVFWlNpelhwTVpVY0Q5anAyTDFOT2JxNjVUc1k3Ykt2M0tMdWdycGJtakV4aGdpCnBEN0FuY2RNVmRvMjh6SjQ4ZEJkRWR1dUMrQVpjdmlBZkphMVZKVW5FdFVRTWlWeE02cEI2MzV2ODFDMkF3YmEKMjE5QmNwYjlGQTNWdk9kN2J1UU5uZjFTa2lzVXJzbUZrQlkvSU1xMHVTTnpjcjVMNW5nMU1xTkI0V3lEN21nWgpTMkE3TTdZNWFWTTcxWVdnekQ2ZlpBRnVPRGk4K2k2MTFLNnRCdExkbDZmK3dKeHY5OGdBWU9vT3VHNlJFZDIwCmR2N056ZWcxMGtBb0IxMDRUWkVmOXBOY094ZTloZklqMk13dVo4ZG9qc0NwOUVzcmUvU2xoWWRXbTQ0eGo2V0wKNTl5UG9wcGFrSXQ1TitIVkI5KzZieVFpOUxCTWFRPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZFVENDQXZtZ0F3SUJBZ0lVVjJMUTE5aUNJR1lzL3NhWTlDWkxvMkN3TVRrd0RRWUpLb1pJaHZjTkFRRU4KQlFBd0dERVdNQlFHQTFVRUF3d05jMlZzWm5OcFoyNWxaQzFqWVRBZUZ3MHlOVEF6TWpRd01ETXdNek5hRncweQpOakF6TWpRd01ETXdNek5hTUJneEZqQVVCZ05WQkFNTURYTmxiR1p6YVdkdVpXUXRZMkV3Z2dJaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUNqbFlYVllxbXZpYmFmc1RxQW0wVlBhS01meUZkVk1oZnMKZFdyY0k0U1ZlZWxjb2I0R05kWHZOYmFUUFhGTytMNUUyNGVQaHY2NksvSkxFN08yUG5ZYm1lb1YwTzNnOTZPQQpVZTgwQTR0NHd5bUFOd0pKU0hOOXZWalpkMmErSDczTzllNXQydURVVlh2Nkc3MGdxNEFLbTNWVFgxTENwc2FaCnByTFh6Z24zTmxDaExoRERVRUtOZUZuU2dUWXlMeGdlQzk1RHAwZ3RId0tMQVpndjdHZUN0WnVVbkVqamhaQ20Kei9JNjByUjl2NUxyS3dLSitkelU5eE5JRXpkVTBYeHBYdkJyd0tzZVR5UVBLQzl6T05mNTZHcXlNajJweXYvVgpyS1pGRWdiemNGSThlS2gwc0o0eHZkcXJWNXJ0WUp6bjIrY01ZZ2ZTL2IzK01VWFk3OHVCVVNyRjJZY0NvdTh0CndLUHVBdjZROHFSTlFCeW5JSnYycjU3eWxQdncwWERlOVdsSlJrZFo2dk9GdFY3UkEwVkFIWmNNMWRwS1JSTjkKTGFyYUd5SzlCdHp5Z2k4d055cFlzd3hEMmJjMUZtSXdMWEZLT0FvU3U3V2tVb0J4cG10V2w4VGhVVGdkMkxNSgpDYi91cHF3ZEJIKzJRck5RRzlBLzg1NXcyT3FsQUFzeExxdFNHd1ozTE1OTk1naURpaTh3UWNlcTBCVXhiaExwCjA0R2MraVhBWURqRmd3a0RROXNYSldKM3lRVTZpZGpjRFc5T2Y5RFBTb0dra3RmbE8zNXc5SFZ1OE96R0V4L1gKNWw5ZExacDMzdWpHVlRLUnZJUEpIRDVkcWdGRFNuV1NsWXZMVjBaM3RVNkJFQnlHekJvVVo3OFlEQWVUVWNNRApPWmYwMis0c2V3SURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVZT1QreG80NjFnUFJNRHFYdXRnaFVhRWdCS0V3Ckh3WURWUjBqQkJnd0ZvQVVZT1QreG80NjFnUFJNRHFYdXRnaFVhRWdCS0V3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBTkJna3Foa2lHOXcwQkFRMEZBQU9DQWdFQUVtNzhyOWQ2cHFqblhRYldQeTBOa1FwKzlyaFlHMWVaU0M4Uwo2T2I5TWtPMXZDSkxoYmZQN0JkcEh2RGh0aDlna081dzc4eERoNnpOOGRTMmkyN0xqK0RQQTVRbXpLVEsvZDVZClZzUDZOQWtld2c5M2poVUUrdFkxVks0UTVSWEg4czN6eXlLNVBGdmhTMTJoS1FyZnVWQmJXeEsya1RYVkl6MmgKb3d6eFBEVjF5dUhpYXdsRmVMV1lWckRaOWtnNEx0OGNySEFMa05hOFNUczIrZVRDNFZlUzc3aHdURkpKRmVWTgoya3c0WTh6ajZ6b3crSUVaR2MvR2xRZVFXMGZZNTE1Z2tXNjVvdkNIam55UnVBNkxNakE2QkFFU2twRkx2SEsxClZPWnAweDBVemJxcXhNZUIyMTd2bEk5OTNybUFPRlBmRjB4WitoZWQzNUNybGVaQlg4MzF2dDZVZ01VSG5GeTEKUExZSXRRZWp1a2dzZU1pWVR2eFR5ak1UVzBkTDRoS05sL2VGKzZyTS9ybGZobmIzZWx2S2ZrNUh1c1BWa0N2OQpmZndMOE5UYUlqY0RMcVRocGRHOTYvNkJoWXFwQ1hidi85bmQ5R3NDcEN5Lzl0eXp1M0toWTBoVVRzNzI0aHF4Ci9pa3JGUlg2TUFJbkpDZjVkU1VEeWt6ZVVtS0hFUlAwL1VJVHozZWZlNEpGdkZDWUtYRGR2a1RSZ2pOSmtTMlYKVCtRcVNETktPMytwZ2RseXdwSG1uTXNESEJBR1hnUENSRW5wWmM2T0cwR1JJa2hMd3ZlVmdLR0gzTzFzOURtMwpUZjU5UkdOYms2UWN5dVlXYkVXcENRTXJ6eHVJUTMvb2pvVisyMmNPOXB5aTBLMDh2b1lEVDdObnAxNW5wbWhiCjFZSjlWRGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
type: Opaque
---
apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: mq01ha
  namespace: cp4i-mq
spec:
  version: 9.4.2.0-r1
  license:
    accept: true
    license: L-QYVA-B365MB
    use: "NonProduction"
  pki:
    keys:
    - name: default
      secret:
        secretName: mq01ha-qm-tls
        items:
          - tls.key
          - tls.crt
          - ca.crt
  web:
    console:
      authentication: {}
      authorization: {}
    enabled: true
  securityContext:
    initVolumeAsRoot: false
    readOnlyRootFilesystem: false
  telemetry:
    tracing:
      instana:
        enabled: false
        protocol: http
  queueManager:
    name: mq01ha
    mqsc:
      - configMap:
          name: mq01ha-mqsc
          items:
            - mq01ha-mqsc.mqsc
    availability:
      type: NativeHA
      tls:
        secretName: mq01ha-qm-tls
      nativeHAGroups:
        local:
          name: recovery_group
          role: Recovery
          route:
            enabled: true
    storage:
      persistedData:
        enabled: true
        class: ocs-storagecluster-ceph-rbd
      queueManager:
        enabled: true
        class: ocs-storagecluster-ceph-rbd
      recoveryLogs:
        enabled: true
        class: ocs-storagecluster-ceph-rbd
  template:
    pod:
      containers:
        - env:
            - name: MQSNOAUT
              value: 'yes'
          name: qmgr
  route:
    enabled: true
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mq01ha-mq01hachl-ibm-mq-qm
  namespace: cp4i-mq
spec:
  host: mq01hachl.chl.mq.ibm.com
  to:
    kind: Service
    name: mq01ha-ibm-mq
  port:
    targetPort: 1414
  tls:
    termination: passthrough
  wildcardPolicy: None
